#### to deploy your workload in kubernetes you need to have an contianer based image. 
###3you need to invoke an api
apiVersion: v1 ####all the communication to your kubernetes cluster happen using api
kind: Pod ##3pod is an api or i can generalized term for your api to 
metadata:
  name: webserver-multi ##3it should create an pod using metadata and name we are creating a pod
spec: #this is the specification for your pod
  containers: ##inside pod we want to create a container
  - name: webserver ##this is name of the container
    image: nginx:1.14.2 ##the container will be created with image by default it will go to hub.docker.com and download the image 
  - image: busybox
    name: busybox
       
