apiVersion: v1 
kind: PersistentVolume
metadata:
  name: task-pv-volume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce #ReadWriteMany #read
  #persistentVolumeReclaimPolicy: Recycle #recycle delete your pod volume will be there data will be cleaned up
  #immediate: delete your pod volume will be deleted
  ###if you want to mount localsytstem hdd
  hostPath:
    path: /mnt/data
  #this will mount and nfs volume
  #mountOptions:
   # - hard
    #- nfsvers=4.1
  #nfs:
   # path: /tmp
    #server: 172.17.0.2
