apiVersion: v1 
kind: ResourceQuota 
metadata:
  name: test-cpu-quota 
  namespace: quota-demo
spec:
  hard:
    ####this is the hard limit we have define against my ns
    requests.cpu: "200m" ###every pod can request max 200m
    limits.cpu: "300m" ###inside this particular ns we have mac 300m
    