apiVersion: v1
kind: ConfigMap
metadata:
  name: usermanagement-db-creation-script
data:
  mysql_usermgmt.sql: |-
    DROP DATABASE IF EXISTS webappdb;
    CREATE DATABASE webappdb;
--- 
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-password
type: Opaque
data:
  password: ZGJwYXNzd29yZDEx
--- 
apiVersion: v1
kind: Service
metadata:
  name: usermgmt-webapp-clusterip-service
  labels:
    app: usermgmt-webapp
spec:
  type: ClusterIP
  selector:
    app: usermgmt-webapp
  ports:
    - port: 80
      targetPort: 8080
